// Copyright 2026 David Monagle / Monagle Pty Ltd
// SPDX-License-Identifier: MIT

import SwiftProtobufPluginLibrary

/// Emits the `<file>.connect.swift` content for a proto file's services.
///
/// Unary and server-streaming methods use the metadata-aware `ConnectRouter`
/// registrations (`ServerRequest`/`ServerResponse`, trailing `Metadata`), so
/// handlers can read request headers (auth tokens, locales) and return
/// trailing metadata. Client-streaming and bidirectional methods use the
/// stream-based registrations — the router offers no metadata-aware variant
/// for those.
public enum ServiceCodeGenerator {
    public static func generate(
        file: SwiftProtobufPluginLibrary.FileDescriptor,
        namer: SwiftProtobufNamer,
        options: GeneratorOptions
    ) -> String {
        var out = """
            // DO NOT EDIT.
            //
            // Generated by protoc-gen-connect-swift-server.
            // Source: \(file.name)


            """
        for module in neededImports(file: file, options: options) {
            out += "import \(module)\n"
        }
        out += "\n\n"
        for service in file.services {
            emitService(service, namer: namer, access: options.visibility.keyword, into: &out)
            out += "\n"
        }
        return out
    }

    /// Base imports plus modules for cross-module proto dependencies and
    /// user-requested extras; deduplicated, base imports first.
    private static func neededImports(
        file: SwiftProtobufPluginLibrary.FileDescriptor,
        options: GeneratorOptions
    ) -> [String] {
        var imports = ["ConnectServer", "GRPCCore", "SwiftProtobuf"]
        let mapped = options.protoFileToModuleMappings.neededModules(forFile: file) ?? []
        for module in (mapped + options.extraModuleImports).sorted() where !imports.contains(module) {
            imports.append(module)
        }
        return imports
    }

    // MARK: - Per-service emission

    private static func emitService(
        _ service: ServiceDescriptor,
        namer: SwiftProtobufNamer,
        access: String,
        into out: inout String
    ) {
        let typeName = swiftServiceTypeName(service)
        let serviceFQN = service.fullName  // proto: e.g. "helloworld.Greeter"

        // Generate one initializer parameter and stored closure per method.
        out += "/// Connect-server bindings for service `\(serviceFQN)`.\n"
        out += "///\n"
        out += "/// Construct with one closure per RPC method, then call `register(with:&router)`.\n"
        out += "\(access) struct \(typeName): Sendable {\n"

        // Stored closures
        for method in service.methods {
            out += "    \(access) let \(methodPropertyName(method)): \(methodClosureType(method, namer: namer))\n"
        }

        // Initializer
        out += "\n    \(access) init(\n"
        let initParams = service.methods.enumerated().map { (idx, method) -> String in
            let name = methodPropertyName(method)
            let type = methodClosureType(method, namer: namer)
            let comma = idx == service.methods.count - 1 ? "" : ","
            return "        \(name): @escaping \(type)\(comma)"
        }
        out += initParams.joined(separator: "\n")
        out += "\n    ) {\n"
        for method in service.methods {
            let name = methodPropertyName(method)
            out += "        self.\(name) = \(name)\n"
        }
        out += "    }\n\n"

        // register(with:&router)
        out += "    /// Registers all RPC methods on the given `ConnectRouter`.\n"
        out += "    \(access) func register(with router: inout ConnectRouter) {\n"
        for method in service.methods {
            emitRegisterCall(method, serviceFQN: serviceFQN, namer: namer, into: &out)
        }
        out += "    }\n"
        out += "}\n"
    }

    // MARK: - Per-method emission

    private static func emitRegisterCall(
        _ method: MethodDescriptor,
        serviceFQN: String,
        namer: SwiftProtobufNamer,
        into out: inout String
    ) {
        let inputType = namer.fullName(message: method.inputType)
        let outputType = namer.fullName(message: method.outputType)
        let methodName = method.name
        let prop = methodPropertyName(method)

        let registerFn: String
        switch (method.clientStreaming, method.serverStreaming) {
        case (false, false): registerFn = "registerUnary"
        case (false, true):  registerFn = "registerServerStreaming"
        case (true, false):  registerFn = "registerClientStreaming"
        case (true, true):   registerFn = "registerBidirectional"
        }

        out += "        router.\(registerFn)(\n"
        out += "            method: MethodDescriptor(fullyQualifiedService: \"\(serviceFQN)\", method: \"\(methodName)\"),\n"
        out += "            requestType: \(inputType).self,\n"
        out += "            responseType: \(outputType).self,\n"
        out += "            handler: self.\(prop)\n"
        out += "        )\n"
    }

    // MARK: - Naming helpers

    /// Service "helloworld.Greeter" → "Helloworld_GreeterConnectService",
    /// or "<swift_prefix>GreeterConnectService" when the file sets
    /// `option swift_prefix`, matching how the message types are named.
    private static func swiftServiceTypeName(_ service: ServiceDescriptor) -> String {
        // We construct: <typePrefix><ServiceName>ConnectService
        // typePrefix uses the swift_prefix file option / package convention.
        let parts = service.fullName.split(separator: ".")
        let serviceName = parts.last.map(String.init) ?? service.name
        let swiftPrefix = service.file.fileOptions.swiftPrefix
        if !swiftPrefix.isEmpty {
            return "\(swiftPrefix)\(serviceName)ConnectService"
        }
        let pkgParts = parts.dropLast()
        let prefix = pkgParts.map { $0.capitalizedFirst }.joined(separator: "_")
        if prefix.isEmpty {
            return "\(serviceName)ConnectService"
        } else {
            return "\(prefix)_\(serviceName)ConnectService"
        }
    }

    /// "SayHello" → "sayHello"
    private static func methodPropertyName(_ method: MethodDescriptor) -> String {
        let n = method.name
        guard let first = n.first else { return n }
        return String(first.lowercased()) + n.dropFirst()
    }

    /// Closure type for a method, matching ConnectRouter.register* handler signatures.
    /// Unary and server-streaming use the metadata-aware variants.
    private static func methodClosureType(_ method: MethodDescriptor, namer: SwiftProtobufNamer) -> String {
        let inputType = namer.fullName(message: method.inputType)
        let outputType = namer.fullName(message: method.outputType)
        switch (method.clientStreaming, method.serverStreaming) {
        case (false, false):
            // Unary: (ServerRequest<Input>, ServerContext) async throws -> ServerResponse<Output>
            return "@Sendable (ServerRequest<\(inputType)>, ServerContext) async throws -> ServerResponse<\(outputType)>"
        case (false, true):
            // Server-streaming: (ServerRequest<Input>, ServerContext, ServerStreamWriter<Output>) async throws -> Metadata
            return "@Sendable (ServerRequest<\(inputType)>, ServerContext, ServerStreamWriter<\(outputType)>) async throws -> GRPCCore.Metadata"
        case (true, false):
            // Client-streaming: (AsyncThrowingStream<Input, any Error>, ServerContext) async throws -> Output
            return "@Sendable (AsyncThrowingStream<\(inputType), any Error>, ServerContext) async throws -> \(outputType)"
        case (true, true):
            // Bidi: (AsyncThrowingStream<Input, any Error>, ServerContext, ServerStreamWriter<Output>) async throws -> Void
            return "@Sendable (AsyncThrowingStream<\(inputType), any Error>, ServerContext, ServerStreamWriter<\(outputType)>) async throws -> Void"
        }
    }
}

// MARK: - Helpers

extension Substring {
    fileprivate var capitalizedFirst: String {
        guard let first = self.first else { return String(self) }
        return String(first.uppercased()) + self.dropFirst()
    }
}
